### ISSUE TITLE
Incorrect query params

### ISSUE THREAD

**Issue by silamon** [elastic/enterprise-search-php#10]
We're having problems fetching any other page than the default page for the list engine operation with the last published version. 

Looking at the code, it looks like the query_params are incorrect on some release branches: 
https://github.com/elastic/enterprise-search-php/blob/7.15/src/AppSearch/Request/ListEngines.php

While the code on the master branch uses the correct query_params: 
https://github.com/elastic/enterprise-search-php/blob/master/src/AppSearch/Request/ListEngines.php

And one of the older releases uses the correct query_params as well: 
https://github.com/elastic/enterprise-search-php/blob/7.14/src/AppSearch/Request/ListEngines.php

Relevant documentation: https://www.elastic.co/guide/en/app-search/7.15/engines.html#engines-query-list

**Comment by ezimuel** [comment]
@silamon can you report the versions of `enterprise-search-php` and `App Search` server that you are using?
The query parametes can be also passed in the body (as reported [here](https://www.elastic.co/guide/en/app-search/current/api-reference.html#overview-api-references-parameters)). From `7.15` we changed all the `query parameters` of `enterprise-search-php` to be passed in the `body`, to prevent issue like #4. 
Can you report the error message of the issue? Thanks!

**Comment by silamon** [comment]
We're using 7.16 for app search and 7.16 for enterprise search php.  When we want to fetch the second or third page, we always receive the first page as if the parameter we've sent using ListEngines -> SetCurrentPage is ignored. 
We're now using 7.14 for enterprise search php which works for us. 

Relevant code: 
https://github.com/elastic/enterprise-search-php/blob/7.16/src/AppSearch/Request/ListEngines.php#L43

EDIT: "current_page" isn't mentioned anywhere, not in the query params documentation and not in the body documentation.

**Comment by ezimuel** [comment]
@silamon the issue has been fixed in [7.16.0](https://github.com/elastic/enterprise-search-php/releases/tag/v7.16.0) release. Please check and let me know, thanks.

**Comment by silamon** [comment]
Thank you for looking into this! Very much appreciated! 👍
