### ISSUE TITLE
Dynamic properties issue

### ISSUE THREAD

**Issue by averatec1337** [elastic/enterprise-search-php#12]
Since 8.2 dynamic properties are deprecated (https://wiki.php.net/rfc/deprecate_dynamic_properties) and from 9.0 it will throw error.
Prehaps it's good point to consider publishing OAS?

**Comment by gignonje** [comment]
I agree with you on this. Any news from Elastic regarding this issue ?

**Comment by ezimuel** [comment]
@kamil-karkus the dynamic properties deprecation will not affect the `__get()` function used by [Response](https://github.com/elastic/enterprise-search-php/blob/master/src/Response/Response.php#L182) object. I think we should continue to offer this approach but I agree with you that a full type object response based on OAS will be awesome. I'll update on this shortly.
