### ISSUE TITLE
Stable 8 release

### ISSUE THREAD

**Issue by Ekman** [elastic/enterprise-search-php#13]
Would be awesome with a stable 8 release. We've already prepared our move to App Search 8 and just waiting for a stable 8 release before pressing the go button.

**Comment by Ekman** [comment]
@ezimuel any status updates?

**Comment by Ekman** [comment]
@ezimuel is this repository still maintained?

**Comment by ezimuel** [comment]
@Ekman yes, it's still maintained. We had some delay due to `elasticsearch-php` v8. We are working to release 8.0 and 7.17 soon. Sorry for any inconvenience.

**Comment by Ekman** [comment]
@ezimuel Any status updates? Elasticsearch 8 has been out for ~4 months and we don't think it's unreasonable to ask for SDK support at this point.

**Comment by Ekman** [comment]
We are being advised to update our Elastic cloud cluster to version 8 or above by your support. When will it be supported?

> This issue was fixed in Elasticsearch >=8.3. If you’re using traffic filters, the workaround for now is to disable it. If you want to continue using traffic filters, then I’d advise you to already upgrade to 8.x and wait for the release of 8.3 (which is planned somewhere in June).

**Comment by ezimuel** [comment]
@Ekman I just released [v8.0.0](https://github.com/elastic/enterprise-search-php/releases/tag/v8.0.0). Sorry again for the huge delay :sweat: Next week, I'll release 8.1, 8.2.

**Comment by Ekman** [comment]
Thank you!
