### ISSUE TITLE
Weird results when searching a specific item

### ISSUE THREAD

**Issue by Messaoudi-Nagib** [elastic/enterprise-search-php#14]
Hello, 

I have a search bar where customers can search for items. It works pretty well except for one thing and I don't figure out why.

Context : When I search **dynasam**, the engine is returning me items that don't fit with my search query. When i'm adding a **"®"** which correspond to the exact term, I then get the results I want. Even when I'm trying in the query tester, I get weird results as long as I don't add the "®". Also, I have tuned my precision to 2 in the search API.
Do you have any idea/advices why it happens ? (I also tried to add some synonyms sets but nothing has changed).
Thank you, best regards
Nagib

**Comment by ezimuel** [comment]
@Messaoudi-Nagib can you provide some PHP code showing how do you perform the search? Thanks!

**Comment by Messaoudi-Nagib** [comment]
Hi @ezimuel, here is my function I use to make search queries to the engine : 

``` php
function vSearch($client, $szEngine, $szQuery, $nNombreResultats = 50, $nPrecision = 2, $szTag = 'test')
{
	$aResult = array();
	$aResult['meta']['page']['total_results'] = 0;
	if($szQuery != '')
	{
		/* Connection to AppSearch */
		$app = $client->appSearch();

		$search = new Elastic\EnterpriseSearch\AppSearch\Schema\SearchRequestParams();
		$search->page = [
			"current" => 1,
			"size" => $nNombreResultats
		];
                /* By default, I put precision to 2 */
		$search->precision = $nPrecision;
		$search->analytics = new Elastic\EnterpriseSearch\AppSearch\Schema\SimpleObject();
		$search->analytics->tags = [$szTag];
		$search->query = $szQuery;

		/* Sending the query to AppSearch */
		$result = $app->search(
			new Request\Search($szEngine, $search)
		);
		/* Returning the result in an array */
		$aResult = $result->asArray();
	}
	return $aResult;
}
```
I don't really know what is the issue,  but it is for a really specific case, wich is when I use the caracter ® in the search query.
Thank you for taking the time to answer me ! 👍🏼 
Regards
