### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by c-schwan** [elastic/enterprise-search-php#16]
Can you please add php 8.1 support:

Fatal error: During inheritance of ArrayAccess: Uncaught Exception: Deprecated Functionality: Return type of Elastic\EnterpriseSearch\Response\Response::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by ezimuel** [comment]
Fixed in [v7.17.0](https://github.com/elastic/enterprise-search-php/releases/tag/v7.17.0)
