### ISSUE TITLE
Request with proxy

### ISSUE THREAD

**Issue by tony-tran** [elastic/enterprise-search-php#21]
Hi,

I need to create an EnterpriseSearch client with a proxy configuration but I didn't find any mention of how can i add proxy to the client.

Can you help me please ?

**Comment by ezimuel** [comment]
@tony-tran you can configure the proxy using a [PSR-18](https://packagist.org/?query=psr-18) client and pass it in the constructor of the `Client`. For instance, using `Guzzle` that is the default PSR-18 client used by `enterprise-search-php` you can configure a proxy as follows:

```php
use Elastic\EnterpriseSearch\Client;

$guzzle = new GuzzleHttp\Client([
    'proxy' => 'http://localhost:8125'
]);

$client = new Client([
    'host' => 'http://localhost:3002',
    'client' => $guzzle,
    'enterprise-search' => [
        'username' => '<insert here the username>',
        'password' => '<insert here the password>'
    ]
]);
```

You can find more information about proxy configuration in this Guzzle [documentation page](https://docs.guzzlephp.org/en/stable/request-options.html#proxy). Guzzle supports also environmental variables to configure a proxy, you can find it [here](https://docs.guzzlephp.org/en/stable/quickstart.html#environment-variables).

**Comment by tony-tran** [comment]
Thank you for the response @ezimuel.

I found this solution in the meantime, sorry for the disturb.
