### ISSUE TITLE
Weird decoding of HTTP response

### ISSUE THREAD

**Issue by ugnius-dev** [elastic/enterprise-search-php#22]
We've been using an old AppSearch PHP library until now. It worked fine but we decided to update it. When we copied a basic code from examples, we got some errors because of JSON parsing. When we're parsing response as string, we got a bunch of un-encoded bytes. I get some request details when I printed result (ex. new Client(...)->appSearch()->search(...); ). Request details says that response is compressed as GZIP (content-encoding: gzip). Once I decode these bytes, I successfully get normal JSON. Unfortunately, I can't find any settings about compressing a content in configurations of elastic or enterprise-search, but I believe that this is problem not only to us. I think library should decrypt content, if needed, before parsing it. And, how it mentioned before, it somehow worked and working now successfully in old AppSearch library.

**Comment by ezimuel** [comment]
@ugnius-dev I think this is an issue related to `elastic-transport-php` that detects automatically the PSR-18 client using the autodiscovery feature of HTTPlug, see [here](https://github.com/elastic/elastic-transport-php/blob/master/src/TransportBuilder.php#L53). We had a similar issue on `elasticsearch-php`, see [here](https://github.com/elastic/elasticsearch-php/issues/1213).

Can you paste the PHP code that you are using with  `enterprise-search-php`?
I suggest to use Guzzle as HTTP client with the following settings:
```php
use Elastic\EnterpriseSearch\Client;

$client = new Client([
    'client' => new GuzzleHttp\Client,
   // ...
]);
```

**Comment by ezimuel** [comment]
@ugnius-dev I hope you fix the issue. I'm closing this but we can open again if you need more assistance. Thanks.
