### ISSUE TITLE
Not a valid Json: Control character error, possibly incorrectly encode

### ISSUE THREAD

**Issue by bclegaspi** [elastic/enterprise-search-php#31]
I am getting an error from the response from this code:

$engineName = 'videogames';

// Single Search
$search = new Schema\SearchRequestParams('luigi');

$result = $this->appSearch->search(
    new Request\Search($engineName, $search)
);
print_r($result->asArray()); // this is where the error is caught

any help would be appreciated.

**Comment by ezimuel** [comment]
@bclegaspi I think this is an issue of the HTTP transport layer that tries to reuse an existing HTTP library that you have in your `vendor`.  Can you copy & paste your `composer.json` configuration?
Which version of `enterprise-search-php` and `PHP` are you using? Thanks.

To solve the issue, you can require `guzzlehttp/guzzle` and use the `Client` setting are reported here https://github.com/elastic/enterprise-search-php/issues/22#issuecomment-1190308772.

**Comment by bclegaspi** [comment]
Thank you for the response @ezimuel .

I am using v8.4.0 of enterprise-search-php and I'm using php 8, I did make the response work by gzdecoding the string of the response instead of using the asArray() function but I will try to test what you suggested. Although does guzzlehttp/guzzle will not have a conflict with php-http/guzzle7-adapter?

Again thanks for the help.

**Comment by carlos-mg89** [comment]
@bclegaspi could you share a code snippet with the way you decoded the string response?

I'm having the exact same `InvalidJsonException` in the `asArray()` method of the response.

**Comment by carlos-mg89** [comment]
I can confirm that using `GuzzleHttp\Client` with the client constructor makes the responses work as expected.

Example:

```
$client = new Client([
    'client' => new GuzzleHttp\Client(),
    'host' => 'YOUR_HOST_URL',
    'app-search' => [
        'apiKey' => 'YOUR_API_KEY',
    ],
]]);

$app = $client->appSearch();

$searchResults = $result->asArray();
```

**Comment by ezimuel** [comment]
Thanks @carlos-mg89 for the feedback. I also added some notes in the README [here](https://github.com/elastic/enterprise-search-php/blob/main/README.md#psr-18-http-library)
