### ISSUE TITLE
Classes are marked as internal

### ISSUE THREAD

**Issue by adrhumphreys** [elastic/enterprise-search-php#6]
Hey team,

It seems like the expectation for using this library is to use the classes to create requests like so:
```php
$client = new Client(...args);
$result = $client->getAppSearch()
                            ->getSchema(new GetSchema('env'));
```

The above `getAppSearch` returns an instance of `AppEndpoints` which is marked as internal. Then `GetSchema` is marked as internal too.

If these are marked as internal then my assumption is to not use them as they are internal classes for the SDK. However, there's no way to use the SDK without these classes.

**Comment by ezimuel** [comment]
@adrhumphreys thanks for reporting this issue. This is an issue in our code generator that had accidentally put `@internal` in these classes. Sorry for that, we will fix asap.

**Comment by ezimuel** [comment]
@adrhumphreys I solved the issue in the code generator. Starting from release [7.16.0](https://github.com/elastic/enterprise-search-php/releases/tag/v7.16.0), all the classes do not have anymore `@internal`.
