### ISSUE TITLE
Guzzle

### ISSUE THREAD

**Issue by c-schwan** [elastic/enterprise-search-php#7]
Hey guys,

is it possible to support guzzle 6 for both (elastic/transport)?

thx

**Comment by ezimuel** [comment]
Hi @c-schwan can you elaborate why do you need to use Guzzle 6? Thanks.

**Comment by ezimuel** [comment]
@c-schwan I mentioned in #32, you can use Guzzle 6 adding the [php-http/guzzle6-adapter](https://github.com/php-http/guzzle6-adapter).
